### PR TITLE
Wait for sbot before connecting

### PR DESCRIPTION
**Pull request by arj03**
Tests were not passing for me and I noticed it was because we don't wait for sbot to be ready

### CODE REVIEW

**Comment by arj03** [comment]
Maybe [this](https://github.com/ssbc/ssb-ws/blob/master/test/index.js#L32) is a better fix. Still a bit annoying to have to remember that.

**Comment by dominictarr** [comment]
A while ago we realized (mostly thanks to @regular ) that some uses of net.listen were not sync, and also in general sometimes a server starting needed to be async (also: bluetooth) so we added a way wait

so best fix would be to wait for that: https://github.com/ssbc/secret-stack/blob/master/core.js#L168

**Comment by dominictarr** [comment]
though I had a funny feeling that it wasn't such an awkward event name...

**Comment by arj03** [comment]
Thanks. Yeah the naming is a problem with a flat namespace as in ssb-server.

**Pull request closed without merging**
