### PR TITLE
Remove crypto from ssb-client repo, use existing libraries instead

### PR DESCRIPTION
**Pull request by pfraze**
per https://github.com/ssbc/ssb-client/issues/2

@dominictarr I also updated the readme to show key management for desktop and web apps. The existing readme would have the app use sbot's main feed keys, which we don't want. You have any objections to what I did instead?

### CODE REVIEW

**Comment by dominictarr** [comment]
okay this looks good, now we just need to change `sbot.add` to be the raw `SecureScuttlebutt#add`, not the `Feed#add`

**Comment by dominictarr** [comment]
okay lets merge!

**Comment by pfraze** [comment]
https://github.com/ssbc/scuttlebot/pull/134 has the updates we need, including the local auth

I renamed `add` to `publish` for adding to the main feed (which phoenix needs) but now we're not using publish anywhere, so....... what should we do there?

**Comment by pfraze** [comment]
Im thinking we may still want the publish function, though maybe with another name? so you can post to the main feed from the console

**Pull request merged**
