### PR TITLE
Horrible, horrible localStorage.ws_remote hack

### PR DESCRIPTION
**Pull request by ezdiy**
See %LnwGZELLQ6mxAiidkyrGOY0xF7kKGAr/6LL13lePWuI=.sha256 convo for context.

tl;dr: it's either this 2 line change here, or ~100 line refactor between patchbay, ssb-config and ssb-client to support ws there.

### CODE REVIEW

**Comment by dominictarr** [comment]
can you give me some more context around why this the refactor is so big?
last I checked an address with `ws://<host>:<port>~shs:<..>` etc should work

**Comment by dominictarr** [comment]
riiiight, it's interactions between `rc` which uses the sync filesystem api and browserify brfs etc. this is part of why I was against using any fancy browserify stuff (bulkify) but sometimes it's better to have collaborators than be right. 

I guess i was perplexed why you needed to add a `ws_remote` when it already has `remote` which is actually only used by the liteclient.

**Comment by dominictarr** [comment]
oh, I'm sorry I was talking about something different... at some point...hmm

**Comment by dominictarr** [comment]
sorry, I got confused because nearly exactly this code used to be in patchbay, but it got obliterated with the move to patchcore (I havn't worked on it in a while)

https://github.com/ssbc/patchbay/blob/v6.10.5/config.js#L5-L7

but now the config code has migrated to https://github.com/ssbc/patchcore/blob/master/config.js
(which is used by both patchwork and patchbay)

I feel that is the right place for an ugly hack (closer to the applications) and ssb-client should stay clean. how does that sound?

**Comment by ezdiy** [comment]
@dominictarr Patchbay no longer works that way. It relies on config being loaded, and rc and ssb-config nukes the config for browser, so there is no config.

How does ugly hack of hardcoding it into https://github.com/ssbc/patchcore/blob/master/sbot.js#L47 solve anything again?

**Comment by dominictarr** [comment]
I think we can make this work just changing ssb-config. it just merges in some config from localStorage (instead of calling rc) that means you'll be able to set a `remote` and patchcore will just work.

**Comment by ahdinosaur** [comment]
> but now the config code has migrated to https://github.com/ssbc/patchcore/blob/master/config.js
(which is used by both patchwork and patchbay)
>
> I feel that is the right place for an ugly hack (closer to the applications) and ssb-client should stay clean. how does that sound?

@dominictarr @ezdiy hey, maybe the best way to handle these "hacks" is by using depject modules to override default behavior: https://github.com/ssbc/patchbay/pull/100#issuecomment-293861288

**Comment by ezdiy** [comment]
@dominictarr Yea,

```
@@ -6,7 +6,7 @@ exports.create = (api) => {
   var config
   return nest('config.sync.load', () => {
     if (!config) {
-      config = Config(process.env.ssb_appname)
+      config = Config(process.env.ssb_appname, typeof localStorage !== 'undefined' && localStorage.remote || {})
       config.manifest = require('./manifest.json')
     }
     return config
```

However that hack is no better than the previous one. Not sure why one module should be targeted with my ugly code *more* than another.

A fix along the "proper" lines:

```
@@ -53,7 +55,7 @@ module.exports = function (name, defaults, argv, parse) {
   ]))
 }

-if(!module.parent) {
+if(!module.parent && process.argv[2]) {
   console.log(
     JSON.stringify(module.exports(process.argv[2]), false, 2)
   )
```

But I reckon you're not keen on supporting rc/ssb-config....

**Comment by dominictarr** [comment]
oh there is definitely ugly modules and clean modules. at least try and keep the ugly code contained

**Pull request closed without merging**
